# Copyright 2026 Dynamo Foundry LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# See the LICENSE file for details.
"""Generate the app icon (assets/icon.ico + icon.png) and the embedded window
icon (synology_share_downloader/icon_data.py). Requires Pillow.

Run:  python scripts/make_icon.py
"""

import base64
import io
import os

from PIL import Image, ImageDraw

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
ASSETS = os.path.join(ROOT, "assets")
PKG = os.path.join(ROOT, "synology_share_downloader")

S = 1024
TOP = (45, 130, 236)      # blue
BOT = (18, 76, 170)


def render():
    img = Image.new("RGBA", (S, S), (0, 0, 0, 0))

    # vertical gradient
    grad = Image.new("RGB", (S, S))
    gd = ImageDraw.Draw(grad)
    for y in range(S):
        t = y / (S - 1)
        col = tuple(int(TOP[i] * (1 - t) + BOT[i] * t) for i in range(3))
        gd.line([(0, y), (S, y)], fill=col)

    # rounded-square mask
    mask = Image.new("L", (S, S), 0)
    ImageDraw.Draw(mask).rounded_rectangle([0, 0, S - 1, S - 1],
                                           radius=int(S * 0.22), fill=255)
    img.paste(grad, (0, 0), mask)

    d = ImageDraw.Draw(img)
    white = (255, 255, 255, 255)
    cx = S // 2

    # download arrow — stem
    stem_w = int(S * 0.135)
    d.rounded_rectangle([cx - stem_w // 2, int(S * 0.20),
                         cx + stem_w // 2, int(S * 0.54)],
                        radius=stem_w // 2, fill=white)
    # download arrow — head
    head_w = int(S * 0.32)
    d.polygon([(cx - head_w // 2, int(S * 0.46)),
               (cx + head_w // 2, int(S * 0.46)),
               (cx, int(S * 0.70))], fill=white)
    # tray / baseline (download-to-disk)
    tray_w, tray_h, tray_y = int(S * 0.54), int(S * 0.095), int(S * 0.73)
    d.rounded_rectangle([cx - tray_w // 2, tray_y,
                         cx + tray_w // 2, tray_y + tray_h],
                        radius=int(tray_h * 0.45), fill=white)

    return img  # full-resolution 1024px master


def main():
    os.makedirs(ASSETS, exist_ok=True)
    master = render()
    icon = master.resize((256, 256), Image.LANCZOS)

    png_path = os.path.join(ASSETS, "icon.png")
    ico_path = os.path.join(ASSETS, "icon.ico")
    icns_path = os.path.join(ASSETS, "icon.icns")
    icon.save(png_path)
    icon.save(ico_path, sizes=[(16, 16), (32, 32), (48, 48),
                               (64, 64), (128, 128), (256, 256)])
    print("wrote", png_path)
    print("wrote", ico_path)

    # macOS .icns (from the 1024 master so Retina sizes are crisp)
    try:
        master.save(icns_path, format="ICNS")
        print("wrote", icns_path)
    except Exception as e:  # Pillow ICNS support varies
        print("skipped icon.icns (%s)" % e)

    # embed a 64px PNG (base64) for the Tk window icon — no data files needed
    buf = io.BytesIO()
    icon.resize((64, 64), Image.LANCZOS).save(buf, format="PNG")
    b64 = base64.b64encode(buf.getvalue()).decode("ascii")
    wrapped = "\n".join(b64[i:i + 76] for i in range(0, len(b64), 76))
    out = os.path.join(PKG, "icon_data.py")
    with open(out, "w", encoding="utf-8") as fh:
        fh.write('# Copyright 2026 Dynamo Foundry LLC\n')
        fh.write('# Licensed under the Apache License, Version 2.0.\n')
        fh.write('"""Base64-encoded PNG of the app icon, for the Tk window icon.\n')
        fh.write('Generated by scripts/make_icon.py -- do not edit by hand."""\n\n')
        fh.write('ICON_PNG_B64 = (\n    "')
        fh.write('"\n    "'.join(wrapped.splitlines()))
        fh.write('"\n)\n')
    print("wrote", out)


if __name__ == "__main__":
    main()
